# Site settings
title: Gary Bryant
description: 'Keep Calm And Gary Only'
url: 'http://www.garybryant.me/'
baseurl: '/'
google_analytics: 'UA-91735523-1'
disqus_shortname: 'garyscode'

author:
  name: 'Gary Bryant'
  #email: code@garybryant.me
  twitter_username: garyscode
  github_username:  garyscode
  linkedin_username:  gary-bryant-7b89b557

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
